import Head from 'next/head'
// import Image from 'next/image'

export default function Home() {
  return (
    <div className='grow overflow-auto'>
      <Head>
        <title>Hackathon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-6'>
        <article className='border rounded-lg p-4 bg-white rounded-md'>
          <h2 className='text-xl border-b border-orange-700/50 py-3 mb-2'>Profile</h2>
          <div className='flex items-center'>
            <div className="rounded-full bg-slate-900 w-24 h-24 mx-5">
            </div>
            <div className='p-2 grow'>
              <h4 className="font-semibold text-xl">Christine Vera</h4>
              <small className='text-gray-500 font-bold'>Software Engineer (I)</small>
              <div className="text-gray-500"><small className='font-bold'>Languages:</small> <small>JavaScript, C++, HTML, CSS</small> </div>
              <div className="text-gray-500"><small className='font-bold'>Hobbies:</small> <small>Travelling 🌍, Dog mom 🐶, Yoga 🧘🏻‍♀️, self-taught coder 👩‍💻</small> </div>
            </div>
            <div className='flex flex-col justify-center p-5'>
              <button className="bg-orange-600 text-white text-sm m-2 p-1 rounded-md">Find Batchmates &rsaquo;</button>
              <button className="bg-orange-600 text-white text-sm m-2 p-1 rounded-md">Book Mentorship Sessions &rsaquo;</button>
            </div>
          </div>
        </article>

        <section className='drop-shadow-xl my-4 p-4 bg-white'>
          <h2 className='text-xl border-b border-orange-700/50 py-3 mb-2'>Mentor Availabilities</h2>
          <div className="flex gap-1">
            <div className="w-40 p-2 bg-slate-200 rounded-md drop-shadow-lg cursor-pointer hover:drop-shadow-xl">
              <div className="rounded-full bg-slate-900 w-20 h-20 mx-auto my-2"></div>
              <h4 className='text-center'>Vienna Shanon</h4>
              <h6 className='text-xs text-center'>Senior Software Engineer</h6>
              <div className="my-4 text-xs">
                <div className='font-bold'>Areas of interest</div>
                <div>Hiking, Dog person, Baking</div>
              </div>
              <p className="text-orange-600 text-xs font-bold">“I have been working in this company for 7 years and am manging a team of 15 engineers.”</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
