import Head from 'next/head'
// import Image from 'next/image'



export default function Home() {
  return (
    <div className='grow overflow-auto'>
      <Head>
        <title>Hackathon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-6'>
        
      </main>
    </div>
  )
}
